export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const RESET_PRICE = "RESET_PRICE";

export const CHECKOUT_SUCCESS = "CHECKOUT_SUCCESS";
export const CHECKOUT_FAIL = "CHECKOUT_FAIL";
export const SUBMIT_ORDER_START = "SUBMIT_ORDER_START";
export const AFTER_CHECKOUT_REDIRECT = "AFTER_CHECKOUT_REDIRECT";
